version: 2
jobs:
    checkout_code:
      working_directory: ~/project
      docker:
        - image: circleci/node:8.10
      steps:
        - checkout
        - save_cache:
            key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            paths: ~/project

    build_dependencies:
      working_directory: ~/project
      docker:
        - image: circleci/node:8.10
      steps:
        - restore_cache:
            key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: Install Dependencies
            command: npm install
        - save_cache:
            key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
            paths:
              - node_modules

    lint:
      working_directory: ~/project
      docker:
        - image: circleci/node:8.10
      steps:
        - restore_cache:
            key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - restore_cache:
            key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: Lint
            command: npm run lint

workflows:
    version: 2
    lint:
        jobs:
             - checkout_code:
                filters:
                  branches:
                    only:
                      - master
             - build_dependencies:
                requires:
                  - checkout_code
                filters:
                  branches:
                    only:
                      - master
             - lint:
                requires:
                  - build_dependencies
                filters:
                  branches:
                    only:
                      - master
