version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.10
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            - run:
                name: Install local dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Source Lint
                command: npm run lint
            - run:
                name: Building
                command: npm run build
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist

workflows:
    version: 2
    build:
        jobs:
            - build
        filters:
            branches:
                only:
                    - master